begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

# ENGINE_ROOT = File.expand_path("./", __dir__)
# APP_RAKEFILE = File.expand_path("./Rakefile", __dir__)
# load 'rails/tasks/engine.rake'
